;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		Buffer-menu-delete
		Buffer-menu-execute
		LaTeX-insert-left-brace
		TeX-command-master
		TeX-insert-backslash
		backward-sexp
		beginning-of-visual-line
		c-electric-delete-forward
		counsel-M-x
		cua--prefix-override-handler
		cua-copy-region
		cua-exchange-point-and-mark
		cua-paste
		delete-selection-repeat-replace-region
		electric-newline-and-maybe-indent
		end-of-visual-line
		eval-defun
		eval-last-sexp
		eval-print-last-sexp
		forward-sentence
		forward-sexp
		indent-for-tab-command
		kill-visual-line
		magit-discard
		markdown-cycle
		mouse-set-region
		org-beginning-of-line
		org-cycle
		org-delete-char
		org-end-of-line
		org-force-self-insert
		org-kill-line
		org-return-indent
		org-self-insert-command
		python-shell-send-buffer
		slime-autodoc-space
		slime-compile-defun
		sly-compile-defun
		sp-backward-sexp
		sp-forward-sexp
		sp-forward-slurp-sexp
		sp-transpose-sexp
		swiper
		transpose-sexps
		transpose-words
		))

(setq mc/cmds-to-run-once
      '(
		markdown-outdent-or-delete
		text-scale-increase
		))
